import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ThemeProvider from "@/components/theme-provider";
import "./globals.css";
import { cn } from "@/lib/utils";
import QueryProvider from "@/components/query-provider";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
   return (
      <html lang="en">
         <body
            className={cn(
               inter.className,
               "flex min-h-screen flex-col items-center justify-center bg-gray-900 px-4 pt-12 sm:px-6"
            )}
         >
            <ThemeProvider
               attribute="class"
               defaultTheme="dark"
               enableSystem
               disableTransitionOnChange
            >
               <QueryProvider>
                  <header className="w-full py-6 text-center">
                     <h1 className="text-4xl font-bold text-white">
                        Live chat app
                     </h1>
                     <p className="mx-auto mt-2 text-lg text-gray-300 lg:w-1/2">
                        Your go-to live chat app where you can effortlessly chat
                        with friends and create groups for endless
                        conversations. Connect, share, and stay close - all in
                        real-time. Let&apos;s start chatting!
                     </p>
                     <div>
                        <h2 className="mb-2 mt-6 text-2xl font-bold text-white">
                           Technologies powering Live chat app
                        </h2>
                        <ul className="list-inside list-disc">
                           <li>Frontend: Built with Next.js</li>
                           <li>
                              Backend: Built with Express.js and PostgreSQL
                           </li>
                        </ul>
                     </div>
                  </header>
                  {children}
                  <footer className="mt-auto w-full py-6 text-center">
                     <p className="text-sm text-gray-300">
                        <a href="https://github.com/radekrzepka">
                           Made by @Radosław Rzepka
                        </a>
                     </p>
                  </footer>
                  <Toaster richColors />
               </QueryProvider>
            </ThemeProvider>
         </body>
      </html>
   );
};

export default RootLayout;
