import type {Metadata} from "next";
import {Inter} from "next/font/google";
import {ThemeProvider} from "@/components/theme-provider";
import "./globals.css";
import {cn} from "@/lib/utils";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
   return (
      <html lang="en">
         <body
            className={cn(
               inter.className,
               "flex min-h-screen flex-col items-center justify-center bg-gray-900 px-4 pt-12 sm:px-6"
            )}
         >
            <ThemeProvider
               attribute="class"
               defaultTheme="dark"
               enableSystem
               disableTransitionOnChange
            >
               <header className="w-full py-6 text-center">
                  <h1 className="text-4xl font-bold text-white">App Name</h1>
                  <p className="mt-2 text-lg text-gray-300">
                     This is a description of the app. It provides a great user
                     experience and a variety of features to help you manage
                     your tasks.
                  </p>
               </header>
               {children}
               <footer className="mt-auto w-full py-6 text-center">
                  <p className="text-sm text-gray-300">
                     <a href="https://github.com/radekrzepka">
                        Made by Radosław Rzepka
                     </a>
                  </p>
               </footer>
            </ThemeProvider>
         </body>
      </html>
   );
}
